# HIPAA Compliance Configuration
# Comprehensive configuration for HIPAA compliance in healthcare AI systems

# Administrative Safeguards
administrative_safeguards:
  security_officer:
    required: true
    contact_email: "security@intelluxe.ai"
    responsibilities:
      - "Implement and maintain security policies"
      - "Conduct security risk assessments"
      - "Manage user access controls"
      - "Oversee security incident response"
  
  workforce_training:
    required: true
    frequency: "annual"
    topics:
      - "HIPAA Privacy Rule"
      - "HIPAA Security Rule"
      - "PHI handling procedures"
      - "Incident reporting"
      - "Password security"
      - "Social engineering awareness"
  
  access_management:
    unique_user_identification: true
    automatic_logoff: true
    logoff_timeout_minutes: 30
    encryption_decryption: true
    
  audit_controls:
    enabled: true
    log_level: "comprehensive"
    retention_period_years: 7
    review_frequency: "monthly"
    
  integrity:
    phi_alteration_destruction_controls: true
    electronic_signature_controls: true
    
  person_or_entity_authentication:
    required: true
    multi_factor_authentication: false  # Would be true in production
    password_requirements:
      minimum_length: 12
      require_uppercase: true
      require_lowercase: true
      require_numbers: true
      require_special_chars: true
      expiration_days: 90
      history_count: 12
  
  transmission_security:
    end_to_end_encryption: true
    encryption_algorithm: "AES-256"
    key_management: true
    integrity_controls: true

# Physical Safeguards
physical_safeguards:
  facility_access_controls:
    required: true
    access_logging: true
    visitor_management: true
    
  workstation_use:
    restrictions: true
    automatic_screen_lock: true
    screen_lock_timeout_minutes: 15
    
  device_and_media_controls:
    disposal_procedures: true
    media_reuse_procedures: true
    accountability_measures: true

# Technical Safeguards
technical_safeguards:
  access_control:
    unique_user_identification: true
    emergency_access_procedure: true
    automatic_logoff: true
    encryption_decryption: true
    
  audit_controls:
    hardware_software_systems: true
    log_phi_access: true
    log_system_access: true
    log_configuration_changes: true
    
  integrity:
    phi_protection: true
    alteration_destruction_controls: true
    
  person_or_entity_authentication:
    verify_user_identity: true
    authentication_methods:
      - "username_password"
      - "api_keys"
      - "jwt_tokens"
    
  transmission_security:
    guard_against_unauthorized_access: true
    encryption_in_transit: true
    encryption_at_rest: true

# Data Classification
data_classification:
  phi_identifiers:
    - "names"
    - "geographic_subdivisions"
    - "dates"
    - "telephone_numbers"
    - "fax_numbers"
    - "email_addresses"
    - "social_security_numbers"
    - "medical_record_numbers"
    - "health_plan_beneficiary_numbers"
    - "account_numbers"
    - "certificate_license_numbers"
    - "vehicle_identifiers"
    - "device_identifiers"
    - "web_urls"
    - "ip_addresses"
    - "biometric_identifiers"
    - "full_face_photos"
    - "other_unique_identifying_numbers"
  
  sensitivity_levels:
    public:
      description: "Information that can be freely shared"
      examples: ["general health education", "public research findings"]
      
    internal:
      description: "Information for internal use only"
      examples: ["system configurations", "internal procedures"]
      
    confidential:
      description: "Sensitive information requiring protection"
      examples: ["patient demographics", "appointment schedules"]
      
    restricted:
      description: "Highly sensitive PHI requiring maximum protection"
      examples: ["medical records", "diagnostic results", "treatment plans"]

# Encryption Requirements
encryption:
  algorithms:
    symmetric:
      approved: ["AES-256", "AES-192", "AES-128"]
      preferred: "AES-256"
      
    asymmetric:
      approved: ["RSA-2048", "RSA-4096", "ECC-P256", "ECC-P384"]
      preferred: "RSA-2048"
      
    hashing:
      approved: ["SHA-256", "SHA-384", "SHA-512"]
      preferred: "SHA-256"
  
  key_management:
    rotation_frequency_days: 365
    key_escrow: true
    key_recovery: true
    secure_key_storage: true
    
  data_at_rest:
    database_encryption: true
    file_system_encryption: true
    backup_encryption: true
    
  data_in_transit:
    tls_version: "1.3"
    certificate_validation: true
    perfect_forward_secrecy: true

# Audit and Monitoring
audit_monitoring:
  events_to_log:
    - "user_authentication"
    - "user_authorization"
    - "phi_access"
    - "phi_modification"
    - "phi_deletion"
    - "system_configuration_changes"
    - "security_policy_changes"
    - "failed_access_attempts"
    - "privilege_escalation"
    - "data_export"
    - "backup_operations"
    - "system_startup_shutdown"
  
  log_retention:
    minimum_years: 7
    maximum_years: 10
    archive_after_years: 3
    
  log_protection:
    integrity_protection: true
    access_controls: true
    encryption: true
    
  monitoring_alerts:
    failed_login_threshold: 3
    unusual_access_patterns: true
    phi_bulk_access: true
    after_hours_access: true
    privileged_account_usage: true

# Incident Response
incident_response:
  response_team:
    security_officer: true
    it_administrator: true
    legal_counsel: true
    compliance_officer: true
    
  incident_types:
    - "unauthorized_phi_access"
    - "phi_data_breach"
    - "system_compromise"
    - "malware_infection"
    - "insider_threat"
    - "physical_security_breach"
    - "vendor_security_incident"
  
  response_procedures:
    detection_time_hours: 1
    assessment_time_hours: 4
    containment_time_hours: 8
    notification_time_hours: 24
    
  breach_notification:
    hhs_notification_days: 60
    individual_notification_days: 60
    media_notification_threshold: 500
    
  documentation:
    incident_log: true
    forensic_evidence: true
    lessons_learned: true
    policy_updates: true

# Business Associate Agreements
business_associates:
  required_clauses:
    - "permitted_uses_disclosures"
    - "safeguard_requirements"
    - "subcontractor_agreements"
    - "breach_notification"
    - "access_amendment_rights"
    - "minimum_necessary"
    - "return_destruction_phi"
    - "compliance_certification"
  
  vendor_assessment:
    security_questionnaire: true
    penetration_testing: true
    compliance_certification: true
    insurance_requirements: true

# Risk Assessment
risk_assessment:
  frequency: "annual"
  scope:
    - "administrative_safeguards"
    - "physical_safeguards"
    - "technical_safeguards"
    - "organizational_requirements"
    - "policies_procedures"
  
  methodology:
    asset_identification: true
    threat_identification: true
    vulnerability_assessment: true
    risk_analysis: true
    risk_mitigation: true
    
  documentation:
    risk_register: true
    mitigation_plans: true
    residual_risk_acceptance: true

# Training and Awareness
training:
  initial_training:
    required: true
    completion_deadline_days: 30
    
  ongoing_training:
    frequency: "annual"
    refresher_training: true
    
  role_specific_training:
    administrators: true
    developers: true
    healthcare_providers: true
    researchers: true
    
  training_topics:
    - "hipaa_overview"
    - "phi_identification"
    - "minimum_necessary"
    - "patient_rights"
    - "breach_prevention"
    - "incident_reporting"
    - "secure_communication"
    - "mobile_device_security"

# Compliance Monitoring
compliance_monitoring:
  internal_audits:
    frequency: "quarterly"
    scope: "comprehensive"
    
  external_audits:
    frequency: "annual"
    third_party_assessment: true
    
  compliance_metrics:
    - "training_completion_rate"
    - "incident_response_time"
    - "audit_finding_resolution_time"
    - "access_review_completion"
    - "policy_update_frequency"
    
  reporting:
    executive_dashboard: true
    compliance_scorecard: true
    trend_analysis: true

# Technology Controls
technology_controls:
  database_security:
    encryption_at_rest: true
    access_logging: true
    query_monitoring: true
    
  application_security:
    secure_coding_practices: true
    vulnerability_scanning: true
    penetration_testing: true
    
  network_security:
    firewall_protection: true
    intrusion_detection: true
    network_segmentation: true
    
  endpoint_security:
    antivirus_protection: true
    device_encryption: true
    remote_wipe_capability: true

# Validation and Testing
validation_testing:
  security_testing:
    frequency: "quarterly"
    penetration_testing: "annual"
    vulnerability_scanning: "monthly"
    
  compliance_testing:
    policy_compliance: "monthly"
    technical_compliance: "quarterly"
    
  disaster_recovery:
    backup_testing: "monthly"
    recovery_testing: "quarterly"
    business_continuity: "annual"
