# Chunked Medical Transcription Configuration
# Comprehensive settings for secure, chunked audio processing with progressive medical insights
# Environment-aware configuration with development/testing/production overrides

# Environment Detection
environment:
  detect_from: ["ENVIRONMENT", "NODE_ENV", "FLASK_ENV"]
  default: "development"
  log_environment_detection: true

# Chunk Processing Configuration
chunk_processing:
  # Audio chunk settings
  # Note: Medical terminology requires longer overlap to prevent cutting multi-syllable words
  # Examples: "esophagogastroduodenoscopy" (25 letters), "pneumoencephalography" (21 letters)
  duration_seconds: 5
  overlap_seconds: 2.5  # Increased from 1.0 for medical terminology
  min_duration_seconds: 2
  max_duration_seconds: 30
  min_overlap_seconds: 1.5  # Increased from 0.5
  max_overlap_seconds: 5.0
  
  # Audio quality settings
  sample_rate: 16000  # Hz for medical-grade audio
  bit_depth: 16
  channels: 1  # mono
  audio_format: "webm"
  codec: "opus"
  bitrate: 128000
  
  # Chunk buffer settings
  overlap_samples_multiplier: 2  # bytes per sample
  crossfade_enabled: true
  crossfade_duration_ms: 50
  audio_artifact_prevention: true
  
  # Context preservation
  context_words_to_preserve: 10
  transcription_tail_overlap: true
  medical_context_carryover: true

# Encryption Configuration
encryption:
  enabled: true
  algorithm: "AES-256-GCM"
  key_size_bits: 256
  nonce_size_bits: 96
  session_key_rotation_interval_seconds: 3600  # 1 hour
  key_derivation_iterations: 100000
  
  # Session key management
  session_key_length: 32
  session_token_length: 32
  min_token_length: 16
  max_token_length: 64
  token_entropy_bits: 256
  
  # Key exchange (asymmetric encryption for session key)
  asymmetric_key_exchange: true
  rsa_key_size: 2048
  ecdh_curve: "P-256"

# WebSocket Configuration
websocket:
  endpoints:
    base_path: "/ws/transcription"
    doctor_prefix: "doctor_"
    patient_prefix: "patient_"
  
  connection:
    timeout_seconds: 30
    heartbeat_interval_seconds: 30
    max_message_size_bytes: 10485760  # 10MB
    compression_enabled: true
  
  protocols:
    secure: "wss"
    insecure: "ws"
    default_port: 8000
    ssl_verify: true
  
  message_types:
    - "initialize_session"
    - "audio_chunk"
    - "medical_insights"
    - "end_session"
    - "error"
    - "heartbeat"

# Progressive Insights Configuration
progressive_insights:
  enabled: true
  
  # Medical entity extraction
  medical_entity_extraction:
    enabled: true
    confidence_threshold: 0.85
    entity_types:
      - "medications"
      - "vital_signs"
      - "symptoms"
      - "diagnoses"
      - "procedures"
      - "allergies"
      - "family_history"
    
    # Entity confidence boosting
    medical_term_confidence_boost: 0.15
    specialized_term_weight: 1.2
    terminology_validation: true
  
  # Clinical alerts
  clinical_alerts:
    enabled: true
    alert_types:
      - "drug_interactions"
      - "abnormal_vitals"
      - "critical_symptoms"
      - "allergy_alerts"
      - "contraindications"
    
    # Alert thresholds
    critical_alert_threshold: 0.9
    warning_alert_threshold: 0.75
    info_alert_threshold: 0.6
  
  # Medical insights processing
  insights_processing:
    batch_insights: false
    real_time_updates: true
    context_window_chunks: 5
    insight_confidence_threshold: 0.7

# SOAP Note Generation
soap_generation:
  auto_generation: true
  
  # SOAP sections
  sections:
    subjective:
      enabled: true
      weight: 1.0
      keywords: ["patient states", "reports", "complains", "feels"]
    
    objective:
      enabled: true
      weight: 1.2
      keywords: ["vital signs", "examination", "observed", "measured"]
    
    assessment:
      enabled: true
      weight: 1.5
      keywords: ["diagnosis", "condition", "impression", "likely"]
    
    plan:
      enabled: true
      weight: 1.3
      keywords: ["treatment", "prescribe", "follow-up", "recommend"]
  
  # Generation triggers
  triggers:
    chunk_interval: 10  # Every 10 chunks
    time_interval_seconds: 60  # Every minute
    content_threshold_words: 50
    manual_trigger: true
  
  # Content processing
  content_processing:
    deduplicate_information: true
    merge_overlapping_content: true
    prioritize_recent_content: true
    maintain_chronological_order: true

# PHI Protection Configuration
phi_protection:
  enabled: true
  detection_level: "standard"  # minimal, standard, maximum
  
  # Detection thresholds
  thresholds:
    minimal: 0.6
    standard: 0.8
    maximum: 0.95
  
  # PHI types to detect
  phi_types:
    - "names"
    - "addresses"
    - "phone_numbers"
    - "ssn"
    - "medical_record_numbers"
    - "account_numbers"
    - "dates"
    - "ages_over_89"
    - "biometric_identifiers"
    - "photos"
    - "email_addresses"
    - "urls"
  
  # Redaction methods
  redaction:
    method: "replacement"  # masking, replacement, removal
    replacement_token: "[REDACTED]"
    preserve_structure: true
    context_aware: true
  
  # Real-time scanning
  real_time_scanning:
    enabled: true
    scan_input: true
    scan_output: true
    alert_on_detection: true

# Session Management
session:
  timeout_minutes: 30
  max_recording_minutes: 60
  min_session_minutes: 5
  max_session_minutes: 180
  
  # Session cleanup
  cleanup_interval_seconds: 300  # 5 minutes
  expired_session_retention_hours: 24
  auto_cleanup_enabled: true
  
  # Session limits
  max_concurrent_sessions: 100
  max_sessions_per_user: 5
  rate_limiting_enabled: true
  
  # Session data
  session_id_format: "session_{random}"
  session_metadata:
    patient_id_encryption: true
    provider_tracking: true
    encounter_type_validation: true
    chief_complaint_storage: true

# Audio Processing Configuration
audio_processing:
  # Input configuration
  input:
    echo_cancellation: true
    noise_suppression: true
    auto_gain_control: true
    preferred_sample_rate: 16000
    channel_count: 1
  
  # Processing pipeline
  pipeline:
    pre_processing:
      normalize_volume: true
      remove_silence: true
      filter_noise: true
    
    chunk_processing:
      validate_audio_format: true
      convert_sample_rate: true
      apply_windowing: true
    
    post_processing:
      enhance_speech: true
      reduce_artifacts: true
      apply_compression: false
  
  # Quality control
  quality:
    min_audio_level: -60  # dB
    max_audio_level: 0    # dB
    silence_threshold: -40 # dB
    quality_score_threshold: 0.7

# User Interface Configuration
ui_settings:
  # Visualization
  audio_visualization:
    enabled: true
    bar_count: 30
    update_interval_ms: 100
    fft_size: 256
    smoothing_factor: 0.8
  
  # Feedback
  feedback:
    show_confidence_scores: true
    enable_audio_feedback: true
    visual_feedback: true
    haptic_feedback: false
  
  # Display settings
  display:
    show_chunk_statistics: true
    show_encryption_status: true
    show_session_progress: true
    auto_scroll_insights: true
    max_insights_displayed: 50
  
  # Progress tracking
  progress:
    show_progress_bar: true
    max_progress_duration_minutes: 30
    update_interval_seconds: 1
    show_elapsed_time: true

# Development and Testing
development:
  mock_mode: false
  debug_logging: false
  save_debug_data: false
  
  # Mock data settings
  mock_transcription:
    enabled: false
    confidence_range: [0.8, 0.95]
    response_delay_ms: [100, 500]
    medical_terms_probability: 0.3
  
  # Testing configuration
  testing:
    skip_encryption: false
    simulate_network_delays: false
    inject_errors: false
    error_rate: 0.0
  
  # Performance testing
  performance_testing:
    enable_metrics: true
    track_processing_time: true
    track_memory_usage: true
    benchmark_encryption: true

# Security Configuration
security:
  # HIPAA compliance
  hipaa_compliance:
    audit_logging: true
    encryption_at_rest: true
    encryption_in_transit: true
    access_controls: true
    data_integrity_checks: true
  
  # Access control
  access_control:
    require_authentication: true
    role_based_access: true
    session_validation: true
    token_verification: true
  
  # Security headers
  security_headers:
    content_security_policy: true
    strict_transport_security: true
    x_frame_options: "DENY"
    x_content_type_options: "nosniff"

# Performance Configuration
performance:
  # Processing limits
  processing:
    max_concurrent_chunks: 10
    chunk_processing_timeout_seconds: 30
    max_memory_usage_mb: 1024
    cpu_usage_threshold: 80
  
  # Caching
  caching:
    enable_session_cache: true
    enable_model_cache: true
    cache_ttl_seconds: 3600
    max_cache_size_mb: 512
  
  # Optimization
  optimization:
    enable_parallel_processing: true
    use_gpu_acceleration: true
    optimize_memory_usage: true
    prefetch_models: true

# Error Handling
error_handling:
  # Retry configuration
  retry:
    max_attempts: 3
    initial_delay_seconds: 1
    backoff_factor: 2.0
    max_delay_seconds: 30
  
  # Error recovery
  recovery:
    auto_recovery_enabled: true
    fallback_to_non_encrypted: false
    continue_on_chunk_error: true
    partial_results_enabled: true
  
  # Error reporting
  reporting:
    log_errors: true
    alert_on_critical_errors: true
    error_notification_threshold: 5
    include_stack_traces: false  # for security

# Logging Configuration
logging:
  # Log levels
  levels:
    root: "INFO"
    transcription: "DEBUG"
    encryption: "INFO"
    websocket: "INFO"
    insights: "DEBUG"
  
  # Log formatting
  formatting:
    include_timestamps: true
    include_session_ids: true
    include_chunk_numbers: true
    sanitize_phi: true
  
  # Log destinations
  destinations:
    console: true
    file: true
    syslog: false
    remote: false

# Environment-Specific Overrides
environments:
  development:
    encryption:
      enabled: false  # Disable for easier debugging
    logging:
      levels:
        root: "DEBUG"
    development:
      mock_mode: true
      debug_logging: true
    performance:
      processing:
        max_concurrent_chunks: 5
  
  testing:
    session:
      timeout_minutes: 5  # Shorter timeouts for tests
    phi_protection:
      enabled: false  # Use synthetic data in tests
    development:
      testing:
        skip_encryption: true
        simulate_network_delays: true
    performance:
      processing:
        max_memory_usage_mb: 512
  
  production:
    encryption:
      enabled: true
      session_key_rotation_interval_seconds: 1800  # More frequent rotation
    security:
      access_control:
        require_authentication: true
    logging:
      levels:
        root: "WARN"
      destinations:
        console: false
        file: true
    performance:
      processing:
        max_concurrent_chunks: 20
        max_memory_usage_mb: 2048

# Integration Settings
integrations:
  # Healthcare API
  healthcare_api:
    base_url: "${HEALTHCARE_API_URL:-https://localhost:8000}"
    timeout_seconds: 30
    retry_attempts: 3
  
  # SciSpacy integration
  scispacy:
    enabled: true
    service_url: "${SCISPACY_URL:-http://localhost:8001}"
    timeout_seconds: 10
    confidence_threshold: 0.8
  
  # Database integration
  database:
    store_sessions: true
    store_transcriptions: true
    store_medical_entities: true
    retention_days: 90

# Compliance and Audit
compliance:
  # HIPAA compliance monitoring
  hipaa:
    audit_all_access: true
    log_phi_detection: true
    monitor_data_flows: true
    alert_on_violations: true
  
  # Audit configuration
  audit:
    log_session_events: true
    log_encryption_events: true
    log_phi_events: true
    log_error_events: true
    audit_trail_retention_days: 2555  # 7 years
  
  # Regulatory compliance
  regulatory:
    data_residency: "US"
    export_controls: true
    consent_management: true
    right_to_deletion: true

# Monitoring and Alerting
monitoring:
  # Health checks
  health_checks:
    enabled: true
    interval_seconds: 30
    endpoint: "/health/transcription/chunked"
    timeout_seconds: 5
  
  # Metrics collection
  metrics:
    enabled: true
    collect_performance_metrics: true
    collect_usage_metrics: true
    collect_error_metrics: true
    collect_security_metrics: true
  
  # Alerting
  alerting:
    enabled: true
    alert_on_errors: true
    alert_on_performance_issues: true
    alert_on_security_issues: true
    notification_channels: ["email", "slack"]

# Feature Flags
feature_flags:
  # Experimental features
  experimental:
    advanced_noise_reduction: false
    ai_powered_chunking: false
    predictive_caching: false
    smart_overlap_adjustment: false
  
  # Beta features
  beta:
    enhanced_medical_entities: true
    real_time_soap_validation: true
    context_aware_insights: true
    adaptive_encryption: false
  
  # Gradual rollout
  rollout:
    percentage_enabled: 100
    user_groups: ["beta_testers", "early_adopters"]
    region_restrictions: []

# Resource Limits
resource_limits:
  # Memory limits
  memory:
    max_heap_size_mb: 2048
    max_chunk_cache_mb: 256
    max_session_cache_mb: 512
    gc_threshold_mb: 1536
  
  # CPU limits
  cpu:
    max_threads: 10
    max_cpu_percent: 85
    thread_pool_size: 5
    processing_queue_size: 100
  
  # Storage limits
  storage:
    max_session_data_mb: 100
    max_audio_cache_mb: 1024
    temp_file_cleanup_hours: 2
    max_log_file_mb: 500