# Healthcare System Configuration
# Environment-specific settings for Intelluxe AI Healthcare Platform

# AI Model Configuration
model:
  temperature: 0.1 # Conservative temperature for medical responses
  max_tokens: 2048 # Standard response length
  top_p: 0.9 # High-quality token selection
  frequency_penalty: 0.0 # No repetition penalty for medical accuracy
  presence_penalty: 0.0 # Allow medical terminology repetition
  timeout_seconds: 30 # 30-second response timeout

# Healthcare Compliance Settings
compliance:
  phi_detection_enabled: true # Always enabled for HIPAA compliance
  audit_logging_enabled: true # Required for healthcare audits
  session_timeout_minutes: 480 # 8-hour healthcare shift
  max_failed_auth_attempts: 3 # Security best practice
  require_mfa: false # Development default (true in production)
  data_retention_days: 2555 # 7-year HIPAA requirement

# Caching Configuration
cache:
  redis_url: "redis://localhost:6379"
  medical_literature_ttl_hours: 24 # Daily refresh for medical literature
  drug_interaction_ttl_hours: 12 # Twice daily for drug interactions
  patient_context_ttl_minutes: 60 # 1-hour session context
  max_cache_size_mb: 256 # 256MB cache limit

# Database Configuration
database:
  postgres_url: "postgresql://intelluxe:secure_password@172.20.0.13:5432/intelluxe"
  max_connections: 20 # Connection pool size
  connection_timeout_seconds: 30 # Connection timeout
  query_timeout_seconds: 60 # Query timeout for complex medical queries
  enable_ssl: true # Always use SSL in production

# Health Monitoring Configuration
monitoring:
  health_check_interval_seconds: 30 # Regular health checks
  alert_threshold_error_rate: 0.05 # 5% error rate alert
  alert_threshold_response_time_ms: 5000 # 5-second response time alert
  log_level: "INFO" # Standard logging level
  enable_performance_metrics: true # Enable performance tracking

# Environment-Specific Settings
debug_mode: false # Disabled by default
api_rate_limit_per_minute: 60 # 1 request per second baseline
jwt_secret_key: "change-in-production" # Must be overridden in production

# Healthcare-Specific Templates and Patterns
templates:
  soap_note_template: |
    SUBJECTIVE: {chief_complaint}
    OBJECTIVE: {vital_signs}
    ASSESSMENT: {clinical_assessment}
    PLAN: {treatment_plan}

  discharge_summary_template: |
    Patient: {patient_name}
    Admission Date: {admission_date}
    Discharge Date: {discharge_date}
    Primary Diagnosis: {primary_diagnosis}
    Procedures: {procedures}
    Medications: {medications}
    Follow-up: {followup_instructions}

# Workflow Configuration
workflows:
  max_encounter_duration_minutes: 120 # 2-hour maximum encounter
  appointment_buffer_minutes: 15 # 15-minute appointment buffer
  insurance_verification_timeout: 300 # 5-minute insurance check
  prescription_review_required: true # Always require prescription review

# =============================================================================
# OPEN WEBUI INTEGRATION SETTINGS
# =============================================================================
open_webui_integration:
  # Feature toggles for Open WebUI medical context
  features:
    enable_medical_context: true
    enable_conversation_continuity: true
    enable_cross_session_memory: true
    enable_medical_topic_extraction: true
    enable_phi_aware_conversations: true
    enable_suggestion_system: true
    
  # Integration modes
  integration_mode: "embedded"  # embedded, api_only, hybrid
  
  # Database settings
  database:
    extend_existing_webui_db: true  # Add tables to existing Open WebUI database
    create_separate_medical_db: false  # Use separate database for medical data
    backup_before_schema_changes: true
    
  # Performance settings for Open WebUI context
  performance:
    max_context_retrieval_time_ms: 500  # Max time to get medical context
    cache_conversation_context: true
    context_cache_size_mb: 50
    enable_async_processing: true
    
  # User experience settings
  user_experience:
    show_medical_context_suggestions: true
    max_suggestions_per_query: 3
    enable_proactive_topic_suggestions: false  # Don't be too aggressive
    suggestion_confidence_threshold: 0.7
    
  # Privacy and compliance for Open WebUI
  privacy:
    default_privacy_level: "standard"  # minimal, standard, enhanced
    allow_user_privacy_control: true
    require_medical_data_consent: false  # Set true for stricter compliance
    enable_conversation_phi_detection: true
    phi_detection_mode: "balanced_mode"  # From phi_detection_config.yaml
    
  # API endpoints for Open WebUI frontend integration
  api_endpoints:
    enable_medical_context_api: true
    api_rate_limit_per_minute: 120
    require_user_authentication: true
    cors_allowed_origins: ["http://localhost:3000", "http://localhost:8080"]
