# Healthcare AI Evaluation Metrics Configuration
# Comprehensive metrics for evaluating healthcare AI systems
# HIPAA-compliant and medically-focused evaluation criteria

# Core AI Evaluation Metrics
core_metrics:
  answer_relevancy:
    threshold: 0.7
    description: "Measures how relevant AI responses are to healthcare queries"
    weight: 1.0
    
  faithfulness:
    threshold: 0.8
    description: "Ensures AI responses are faithful to medical knowledge base"
    weight: 1.2
    
  contextual_precision:
    threshold: 0.7
    description: "Measures precision of medical context understanding"
    weight: 1.0
    
  contextual_recall:
    threshold: 0.7
    description: "Measures recall of relevant medical information"
    weight: 1.0
    
  hallucination:
    threshold: 0.2
    description: "Detects medical hallucinations (lower is better)"
    weight: 1.5
    inverted: true
    
  bias:
    threshold: 0.1
    description: "Detects bias in healthcare recommendations"
    weight: 1.3
    inverted: true
    
  toxicity:
    threshold: 0.05
    description: "Ensures no harmful medical advice"
    weight: 2.0
    inverted: true

# Healthcare-Specific Metrics
healthcare_metrics:
  medical_accuracy:
    threshold: 0.85
    description: "Accuracy of medical information and recommendations"
    weight: 2.0
    evaluation_criteria:
      - "Correct medical terminology usage"
      - "Accurate disease information"
      - "Appropriate treatment recommendations"
      - "Proper medication information"
    
  clinical_reasoning:
    threshold: 0.8
    description: "Quality of clinical reasoning and decision-making"
    weight: 1.8
    evaluation_criteria:
      - "Logical diagnostic reasoning"
      - "Appropriate differential diagnosis"
      - "Evidence-based recommendations"
      - "Risk-benefit analysis"
    
  patient_safety:
    threshold: 0.95
    description: "Ensures patient safety in all recommendations"
    weight: 2.5
    evaluation_criteria:
      - "No harmful recommendations"
      - "Appropriate safety warnings"
      - "Contraindication awareness"
      - "Emergency situation recognition"
    
  drug_interaction_detection:
    threshold: 0.9
    description: "Ability to detect and warn about drug interactions"
    weight: 2.0
    evaluation_criteria:
      - "Major interaction detection"
      - "Contraindication identification"
      - "Allergy consideration"
      - "Dosage appropriateness"
    
  diagnostic_accuracy:
    threshold: 0.8
    description: "Accuracy in diagnostic suggestions and reasoning"
    weight: 1.8
    evaluation_criteria:
      - "Symptom pattern recognition"
      - "Appropriate diagnostic tests"
      - "Differential diagnosis quality"
      - "Red flag identification"
    
  treatment_appropriateness:
    threshold: 0.85
    description: "Appropriateness of treatment recommendations"
    weight: 1.9
    evaluation_criteria:
      - "Evidence-based treatments"
      - "Patient-specific considerations"
      - "Guideline adherence"
      - "Alternative option awareness"

# Compliance and Security Metrics
compliance_metrics:
  hipaa_compliance:
    threshold: 1.0
    description: "HIPAA compliance in all interactions"
    weight: 3.0
    evaluation_criteria:
      - "No PHI exposure"
      - "Appropriate data handling"
      - "Audit trail completeness"
      - "Access control compliance"
    
  phi_protection:
    threshold: 1.0
    description: "Protection of Protected Health Information"
    weight: 3.0
    evaluation_criteria:
      - "PHI detection accuracy"
      - "Appropriate masking/redaction"
      - "Secure data transmission"
      - "Proper data storage"
    
  audit_completeness:
    threshold: 0.95
    description: "Completeness of audit logging"
    weight: 2.0
    evaluation_criteria:
      - "All interactions logged"
      - "Proper timestamp recording"
      - "User identification"
      - "Action tracking"
    
  access_control:
    threshold: 0.95
    description: "Proper access control implementation"
    weight: 2.0
    evaluation_criteria:
      - "Role-based access"
      - "Authentication verification"
      - "Authorization checking"
      - "Session management"

# Performance Metrics
performance_metrics:
  response_time:
    threshold: 5.0
    description: "Response time in seconds (lower is better)"
    weight: 1.0
    inverted: true
    unit: "seconds"
    
  throughput:
    threshold: 10.0
    description: "Requests per second capacity"
    weight: 0.8
    unit: "requests/second"
    
  availability:
    threshold: 0.99
    description: "System availability percentage"
    weight: 1.5
    unit: "percentage"
    
  scalability:
    threshold: 0.9
    description: "System scalability under load"
    weight: 1.2
    evaluation_criteria:
      - "Load handling capacity"
      - "Resource utilization"
      - "Performance degradation"
      - "Recovery time"

# Multi-Agent Workflow Metrics
workflow_metrics:
  agent_coordination:
    threshold: 0.85
    description: "Quality of coordination between healthcare agents"
    weight: 1.5
    evaluation_criteria:
      - "Information sharing accuracy"
      - "Workflow continuity"
      - "Handoff completeness"
      - "Context preservation"
    
  workflow_efficiency:
    threshold: 0.8
    description: "Efficiency of multi-agent healthcare workflows"
    weight: 1.3
    evaluation_criteria:
      - "Minimal redundancy"
      - "Optimal agent selection"
      - "Parallel processing"
      - "Resource optimization"
    
  error_handling:
    threshold: 0.9
    description: "Quality of error handling in workflows"
    weight: 1.8
    evaluation_criteria:
      - "Error detection accuracy"
      - "Graceful degradation"
      - "Recovery mechanisms"
      - "User notification"
    
  data_consistency:
    threshold: 0.95
    description: "Consistency of data across agent interactions"
    weight: 2.0
    evaluation_criteria:
      - "Data synchronization"
      - "Version control"
      - "Conflict resolution"
      - "Integrity maintenance"

# Evaluation Configuration
evaluation_config:
  # Test execution settings
  parallel_execution: true
  max_workers: 4
  timeout_seconds: 30
  retry_attempts: 3
  
  # Data settings
  synthetic_data_only: true
  phi_detection_enabled: true
  audit_logging_enabled: true
  
  # Reporting settings
  detailed_reports: true
  export_formats: ["json", "csv", "html"]
  report_directory: "/opt/intelluxe/logs/evaluation_reports"
  
  # Thresholds for overall evaluation
  overall_pass_threshold: 0.8
  critical_metric_threshold: 0.9
  
  # Critical metrics that must pass
  critical_metrics:
    - "patient_safety"
    - "hipaa_compliance"
    - "phi_protection"
    - "medical_accuracy"
    - "toxicity"

# Test Scenarios Configuration
test_scenarios:
  basic_medical_qa:
    description: "Basic medical question answering"
    test_cases: 50
    complexity: "low"
    
  complex_diagnosis:
    description: "Complex diagnostic reasoning"
    test_cases: 30
    complexity: "high"
    
  drug_interactions:
    description: "Drug interaction detection"
    test_cases: 40
    complexity: "medium"
    
  emergency_scenarios:
    description: "Emergency medical scenarios"
    test_cases: 20
    complexity: "high"
    
  multi_agent_workflows:
    description: "Multi-agent healthcare workflows"
    test_cases: 25
    complexity: "high"
    
  compliance_validation:
    description: "HIPAA and compliance validation"
    test_cases: 35
    complexity: "medium"

# Model Configuration
model_config:
  primary_models:
    - "llama3.1:8b-instruct-q4_K_M"
    - "mistral:7b-instruct-q4_K_M"
  
  evaluation_models:
    - "llama3.1:8b-instruct-q4_K_M"  # For evaluation tasks
  
  model_parameters:
    temperature: 0.7
    top_p: 0.9
    max_tokens: 1000
    timeout: 30

# Integration Settings
integration:
  database:
    host: "localhost"
    port: 5432
    database: "intelluxe"
    
  cache:
    host: "localhost"
    port: 6379
    
  ollama:
    host: "localhost"
    port: 11434
    
  logging:
    level: "INFO"
    file: "/opt/intelluxe/logs/healthcare_evaluation.log"
