"""
Type stubs for medical-mirrors modules to resolve pylance/mypy import issues.
This file provides type hints for the imported medical-mirrors classes.
"""

from typing import Any


# Stub for Config class from medical-mirrors
class Config:
    POSTGRES_URL: str
    CLINICALTRIALS_API: str
    FDA_API_BASE: str
    NLM_ICD10_API: str
    NLM_HCPCS_API: str
    MYHEALTHFINDER_API: str
    EXERCISEDB_API: str
    USDA_FOOD_API: str
    DATA_DIR: str
    LOGS_DIR: str
    REQUEST_DELAY: float
    MAX_CONCURRENT_DOWNLOADS: int
    DEFAULT_MAX_RESULTS: int
    MAX_SEARCH_RESULTS: int

    def get_pubmed_data_dir(self) -> str: ...
    def get_trials_data_dir(self) -> str: ...
    def get_fda_data_dir(self) -> str: ...
    def get_icd10_data_dir(self) -> str: ...
    def get_billing_codes_data_dir(self) -> str: ...
    def get_health_info_data_dir(self) -> str: ...

# Stub for ICD10Downloader
class ICD10Downloader:
    base_url: str
    def __init__(self, config: Config) -> None: ...
    async def __aenter__(self) -> "ICD10Downloader": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    async def download_all_codes(self) -> list[dict[str, Any]]: ...
    def get_download_stats(self) -> dict[str, Any]: ...

# Stub for BillingCodesDownloader
class BillingCodesDownloader:
    def __init__(self, config: Config) -> None: ...
    async def __aenter__(self) -> "BillingCodesDownloader": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    async def download_all_codes(self) -> list[dict[str, Any]]: ...
    def get_download_stats(self) -> dict[str, Any]: ...

# Stub for HealthInfoDownloader
class HealthInfoDownloader:
    def __init__(self, config: Config) -> None: ...
    async def __aenter__(self) -> "HealthInfoDownloader": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
    async def download_all_health_data(self) -> dict[str, list[dict[str, Any]]]: ...
    def get_download_stats(self) -> dict[str, Any]: ...
