name: Copilot Setup Steps for Intelluxe AI Healthcare System

on:
  workflow_dispatch:
    inputs:
      setup_type:
        description: 'Type of Copilot setup to perform'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - network-only
        - permissions-only

jobs:
  copilot-setup-steps:
    runs-on: ubuntu-latest
    name: Setup Copilot for Healthcare AI Development
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Network Access for Healthcare AI Dependencies
      run: |
        echo "=== Configuring Network Access for Intelluxe AI ==="
        
        # Core Ubuntu and Microsoft package repositories
        echo "Allowing access to Ubuntu and Microsoft package repositories..."
        
        # Ubuntu Archive and ESM repositories
        curl -f --connect-timeout 10 http://archive.ubuntu.com/ubuntu/ls-lR.gz > /dev/null || echo "Ubuntu archive check failed"
        curl -f --connect-timeout 10 https://esm.ubuntu.com/ > /dev/null || echo "Ubuntu ESM check failed"
        curl -f --connect-timeout 10 https://motd.ubuntu.com/ > /dev/null || echo "Ubuntu MOTD check failed"
        
        # Microsoft packages (for VS Code, .NET, etc.)
        curl -f --connect-timeout 10 https://packages.microsoft.com/ > /dev/null || echo "Microsoft packages check failed"
        
        # Healthcare AI specific repositories
        echo "Checking healthcare AI infrastructure dependencies..."
        
        # Docker Hub for healthcare container images
        curl -f --connect-timeout 10 https://registry-1.docker.io/v2/ > /dev/null || echo "Docker Hub check failed"
        
        # GitHub for healthcare AI repositories and releases
        curl -f --connect-timeout 10 https://api.github.com/repos/Galdaer/Intelluxe > /dev/null || echo "GitHub API check failed"
        
        # Python Package Index for healthcare AI dependencies
        curl -f --connect-timeout 10 https://pypi.org/simple/ > /dev/null || echo "PyPI check failed"
        
        # Node.js for n8n workflow automation
        curl -f --connect-timeout 10 https://registry.npmjs.org/ > /dev/null || echo "NPM registry check failed"
        
        # Ollama for local LLM infrastructure
        curl -f --connect-timeout 10 https://ollama.com/ > /dev/null || echo "Ollama check failed"
        
        echo "Network access verification completed"
        
    - name: Configure Copilot Domains and Allowlist
      run: |
        echo "=== Configuring Copilot Domain Allowlist ==="
        
        # Core required domains for Intelluxe AI development
        cat << 'EOF' > copilot-domains.txt
        # Ubuntu Package Repositories
        http.tcp.archive.ubuntu.com
        https.tcp.esm.ubuntu.com  
        https.tcp.motd.ubuntu.com
        
        # Microsoft Package Repository
        https.tcp.packages.microsoft.com
        
        # Healthcare AI Infrastructure Domains
        https.tcp.github.com
        https.tcp.api.github.com
        https.tcp.raw.githubusercontent.com
        
        # Docker Infrastructure for Healthcare Containers
        https.tcp.registry-1.docker.io
        https.tcp.index.docker.io
        https.tcp.docker.io
        
        # Python Package Index for Healthcare AI Dependencies
        https.tcp.pypi.org
        https.tcp.files.pythonhosted.org
        
        # Node.js for n8n Healthcare Workflow Automation
        https.tcp.registry.npmjs.org
        https.tcp.nodejs.org
        
        # Ollama for Local LLM Infrastructure
        https.tcp.ollama.com
        https.tcp.registry.ollama.ai
        
        # PostgreSQL for Healthcare Data Management
        https.tcp.download.postgresql.org
        https.tcp.ftp.postgresql.org
        
        # Redis for Healthcare Session Management
        https.tcp.download.redis.io
        
        # Healthcare AI Model Repositories
        https.tcp.huggingface.co
        https.tcp.cdn-lfs.huggingface.co
        
        # Medical Research APIs (Read-only)
        https.tcp.pubmed.ncbi.nlm.nih.gov
        https.tcp.clinicaltrials.gov
        https.tcp.api.fda.gov
        
        # VS Code and Development Tools
        https.tcp.marketplace.visualstudio.com
        https.tcp.vscode.dev
        https.tcp.code.visualstudio.com
        
        # Git and Version Control
        https.tcp.git-scm.com
        
        # Healthcare Compliance and Security Tools
        https.tcp.cve.mitre.org
        https.tcp.nvd.nist.gov
        EOF
        
        echo "Domain allowlist configured for healthcare AI development"
        cat copilot-domains.txt
        
    - name: Setup Healthcare AI Development Environment
      run: |
        echo "=== Setting up Healthcare AI Development Environment ==="
        
        # Verify Python for healthcare AI components
        python3 --version
        pip3 --version
        
        # Verify Node.js for n8n workflow automation
        node --version || echo "Node.js not available"
        npm --version || echo "NPM not available"
        
        # Verify Docker for healthcare container orchestration
        docker --version || echo "Docker not available"
        
        # Verify shell tools for Intelluxe AI scripts
        bash --version
        shellcheck --version || echo "ShellCheck not available"
        
        # Create development directories matching Intelluxe structure
        mkdir -p {agents,core,data,infrastructure,services,docs,test}
        
        echo "Healthcare AI development environment verification completed"
        
    - name: Validate Copilot Instructions
      run: |
        echo "=== Validating Copilot Instructions ==="
        
        if [ -f ".github/copilot-instructions.md" ]; then
          echo "✓ Copilot instructions file found"
          echo "Instructions file size: $(wc -l < .github/copilot-instructions.md) lines"
          
          # Check for key healthcare AI sections
          if grep -q "Healthcare Philosophy" .github/copilot-instructions.md; then
            echo "✓ Healthcare philosophy section found"
          fi
          
          if grep -q "Medical Safety" .github/copilot-instructions.md; then
            echo "✓ Medical safety principles found"
          fi
          
          if grep -q "HIPAA" .github/copilot-instructions.md; then
            echo "✓ HIPAA compliance guidelines found"
          fi
          
          if grep -q "PHI/PII" .github/copilot-instructions.md; then
            echo "✓ Privacy protection guidelines found"
          fi
          
        else
          echo "⚠️ Copilot instructions file not found"
          exit 1
        fi
        
    - name: Setup Healthcare AI Compliance Checks
      run: |
        echo "=== Setting up Healthcare AI Compliance Checks ==="
        
        # Create compliance validation script
        cat << 'EOF' > compliance-check.sh
        #!/bin/bash
        
        echo "Performing healthcare AI compliance validation..."
        
        # Check for PHI/PII exposure in code
        echo "Checking for potential PHI/PII exposure..."
        if grep -r -i "ssn\|social.*security\|patient.*id\|medical.*record" --include="*.py" --include="*.sh" --include="*.js" . 2>/dev/null; then
          echo "⚠️ Potential PHI/PII references found - review for compliance"
        else
          echo "✓ No obvious PHI/PII references found"
        fi
        
        # Check for external API calls that could leak data
        echo "Checking for external API calls..."
        if grep -r -i "requests\.\|curl.*http\|wget.*http" --include="*.py" --include="*.sh" . 2>/dev/null | grep -v localhost | grep -v 127.0.0.1; then
          echo "⚠️ External API calls found - verify no PHI/PII transmission"
        else
          echo "✓ No external API calls detected"
        fi
        
        # Check for cloud service dependencies
        echo "Checking for cloud service dependencies..."
        if grep -r -i "aws\|azure\|gcp\|google.*cloud\|amazonaws" --include="*.py" --include="*.sh" --include="*.yml" . 2>/dev/null; then
          echo "⚠️ Cloud service references found - verify on-premise compliance"
        else
          echo "✓ No cloud service dependencies detected"
        fi
        
        echo "Healthcare AI compliance check completed"
        EOF
        
        chmod +x compliance-check.sh
        ./compliance-check.sh
        
    - name: Setup Development Tools for Healthcare AI
      run: |
        echo "=== Setting up Development Tools for Healthcare AI ==="
        
        # Install Python packages for healthcare AI development
        pip3 install --user flake8 mypy pytest pytest-cov black
        
        # Verify healthcare AI specific tools
        echo "Python linting tools installed for code quality"
        flake8 --version
        mypy --version
        pytest --version
        black --version
        
        # Setup shell linting for Intelluxe AI scripts
        if command -v shellcheck >/dev/null 2>&1; then
          echo "✓ ShellCheck available for shell script validation"
        else
          echo "⚠️ ShellCheck not available - install for script validation"
        fi
        
    - name: Generate Development Summary
      run: |
        echo "=== Intelluxe AI Healthcare System - Copilot Setup Summary ==="
        echo ""
        echo "🏥 **HEALTHCARE AI DEVELOPMENT ENVIRONMENT READY**"
        echo ""
        echo "**Project**: Intelluxe AI - Privacy-First Healthcare AI System"
        echo "**Focus**: On-premise clinical deployment with administrative support"
        echo "**Safety**: NO medical advice - administrative/documentation only"
        echo ""
        echo "**Key Components Configured:**"
        echo "- ✓ Network access for healthcare AI dependencies"
        echo "- ✓ Domain allowlist for secure development"
        echo "- ✓ HIPAA compliance validation tools"
        echo "- ✓ Privacy protection guidelines"
        echo "- ✓ Development environment verification"
        echo ""
        echo "**Next Steps:**"
        echo "1. Review .github/copilot-instructions.md for development guidelines"
        echo "2. Follow PHASE_0.md through PHASE_3.md for implementation roadmap"
        echo "3. Use universal-service-runner.sh for all service deployments"
        echo "4. Test with clinic-bootstrap.sh for infrastructure setup"
        echo "5. Validate compliance with ./compliance-check.sh"
        echo ""
        echo "**Remember**: All PHI/PII must remain on-premise!"
        echo "**Medical Safety**: No diagnosis, treatment, or medical advice features!"
        echo ""
        echo "Happy healthcare AI development! 🔬🤖"

env:
  # Healthcare AI specific environment variables
  INTELLUXE_ENV: development
  HEALTHCARE_COMPLIANCE: enabled
  PHI_PROTECTION: strict
  
  # Development tool configurations
  PYTHONPATH: /home/runner/work/Intelluxe/Intelluxe
  NODE_ENV: development
  
  # Security configurations
  DISABLE_EXTERNAL_APIS: true
  ENABLE_AUDIT_LOGGING: true
